### ISSUE TITLE
DOF loading: fails to compile ustack helper

### ISSUE THREAD

**Issue by sax** [sax/dtrace-stacktraces#2]
```
rubyland: I am trying to load /vagrant/dtrace-stacktraces/ext/dtrace/stacktraces/ruby_dtrace_ustack.d
c land: I am trying to load /vagrant/dtrace-stacktraces/ext/dtrace/stacktraces/ruby_dtrace_ustack.d
/vagrant/dtrace-stacktraces/lib/dtrace/stacktraces.rb:14:in `load_ustack_helper': compile failed: errno 1005: line 15: extraneous argument '(null)' ($7 is not referenced) (fatal)
        from /vagrant/dtrace-stacktraces/lib/dtrace/stacktraces.rb:14:in `<top (required)>'
        from run.rb:3:in `require'
        from run.rb:3:in `<main>'
```

**Comment by sax** [comment]
@pmenglund Have you seen this error before? When I get a chance I'll package up the scripts that I've been using to manage my Vagrant test environment.

**Comment by pmenglund** [comment]
Unfortunately not!

**Comment by sax** [comment]
I'll add more information to this ticket when I have time to track down where it's happening in the Illumos source code.

**Comment by sax** [comment]
@chrisa does this error ring a bell for you? I'm trying to reverse engineer your Perl ustack helper into Ruby, and it is slow going. Obviously the ustack helper itself is just a hello world, but I thought I would not be able to really work on that until getting something loading into the kernel.

https://github.com/sax/dtrace-stacktraces/blob/master/ext/dtrace/stacktraces/ruby_ustack.c
https://github.com/sax/dtrace-stacktraces/blob/master/ext/dtrace/stacktraces/ruby_dtrace_ustack.d

Thanks for any comments you have time to give. At this point I have very little understanding of the internals of dtrace, but I assume that the near future will take me deep into the Illumos source code to get this working.

**Comment by chrisa** [comment]
I think the compile error you're getting is because the code still provides all of the arguments I needed in the Perl version, but those arguments aren't consumed by your Hello World D code -- and that's a fatal error.

If you make your argc be 1, and just pass "ruby" as the first argument, that should at least compile?

You can see how I'm consuming the arguments with $1 -> $7 in the D source, here:

https://github.com/chrisa/perl-Devel-DTrace-Helper/blob/master/lib/Devel/DTrace/perlhelper.d

**Comment by sax** [comment]
Ahhhh, okay. Thanks, that makes a lot of sense. Right now I'm at the parroting stage... maybe I do need to spend some time getting into the dtrace source code.
